import type { Metadata } from "next";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {

  return (
    <html>
      <body className="min-h-screen bg-[#F5F0E8] font-body">
          <Header />
          <main className="pt-16">
            {children}
          </main>
          <Footer />
      </body>
    </html>
  );
}